### ISSUE TITLE
Feature Request:  Custom width search panel

### ISSUE THREAD

**Issue by thomasTAT** [Quorafind/Obsidian-Float-Search#38]
### Feature Requested

Feature Request: Custom width search panel

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/109513632/7afbebbd-6659-4291-8298-a2a85d5d8606)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
You can set the style via

```css
.modal.float-search-modal {
  width: 800px;
}
```
