### ISSUE TITLE
Feature Request: [Feature Request] CSS → Style when Preview is Focused

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Float-Search#7]
### Feature Requested

Hello @Quorafind !!!!

Would you mind to expose in `style.css` a way to let us change the style of the **Preview** when the **Preview is focused** ?

💡 I am thinking about changing the `background-color` or adding a `border` when the Preview is focused 

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 

Have a great day 🌞

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Available in latest version: 
```css
.float-search-modal-file-ctn:has(.mod-active) {
    border-bottom: 3px solid var(--color-accent);
}

.float-search-modal-file-ctn:has(.mod-active) .cm-scroller {
	background-color: var(--background-primary);
}
```
